version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:ro
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
